import { Source } from "types/types.ts";

export const sources = [
	{
		name: "BBC Sinhala",
		language: "si",
		url: "https://tinyurl.com/wlvo8td",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "Neth News",
		language: "si",
		url: "https://tinyurl.com/spyq9lx",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "News.lk",
		language: "si",
		url: "https://tinyurl.com/y35lznud",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "Ada",
		language: "si",
		url: "https://tinyurl.com/y5h4lxyy",
		provider: "rss_provider.ts",
		enabled: false,
	},
	{
		name: "Hiru News",
		language: "en",
		url: "https://tinyurl.com/yyez4kwf",
		provider: "rss_provider.ts",
		enabled: false,
	},
	{
		name: "Daily News",
		language: "en",
		url: "https://tinyurl.com/y6qkfp9b",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "News.lk",
		language: "en",
		url: "https://tinyurl.com/w28nfht",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "Gossip Lanka",
		language: "en",
		url: "https://tinyurl.com/qlovo8o",
		provider: "rss_provider.ts",
		enabled: false,
	},

	{
		name: "JVP News",
		language: "ta",
		url: "https://tinyurl.com/uws8hxb",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "Tamilwin",
		language: "ta",
		url: "https://tinyurl.com/ulugr2w",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "BBC",
		language: "ta",
		url: "https://tinyurl.com/vjh89nj",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "Srilanka Mirror",
		language: "en",
		url: "https://tinyurl.com/v7ag5x9",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "Dinamina",
		language: "si",
		url: "https://tinyurl.com/ydfs3wv3",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "Sunday Observer",
		language: "en",
		url: "https://tinyurl.com/uzoj5dy",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "BBC",
		language: "en",
		url: "https://tinyurl.com/w2juyax",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "Lanka Puvath",
		language: "si",
		url: "https://tinyurl.com/txz9gtp",
		provider: "rss_provider.ts",
		enabled: true,
	},
	{
		name: "Colombo Page",
		language: "en",
		url: "https://tinyurl.com/upttpum",
		provider: "rss_provider.ts",
		enabled: true,
	},
] as Array<Source>;
